# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev
- main


stages:
  - stage: build_dev
    pool:
      vmImage: ubuntu-latest
    jobs:
    - job: dev_job
      variables:
            imageName: 'swapi' 
            isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
      steps:
      - script: |
          docker build . -t $(imageName)
          docker images
        displayName: 'Build container image'
      - script: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
        displayName: Install sysdig scanner
      - script: |
          sysdig-cli-scanner --apiurl https://app.au1.sysdig.com swapi
        displayName: Run security scan
      condition: and(succeeded(), eq(variables.isDev, 'true'))

  - stage: build_main
    jobs:
    - job: Main_Branch
      variables:
            imageName: 'swapi' 
            isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
            mytoken: $(ORCA_API_KEY)
      steps:
      - script: |
          docker build . -t $(imageName)
          docker images
        displayName: 'Build container image'
      - script: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
        displayName: Install orca scanner
      - script: |
          docker images
          SECURE_API_TOKEN=${SECURE_API_TOKEN} ./sysdig-cli-scanner --apiurl ${SYSDIG_API_URL} ${{variables.imageName}}
        displayName: Run container image security scan
      - script: |
          echo $(Build.SourceBranch)
        displayName: Echo the REF (branch)
      condition: and(succeeded(), eq(variables.isMain, 'true'))
