apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swapi-api
  name: swapi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swapi-api
  template:
    metadata:
      labels:
        app: swapi-api
    spec:
      containers:
      - image: public.ecr.aws/o5z5d3z9/svk:latest
        imagePullPolicy: Always
        name: swapi-api
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: swapi-svc
spec:
  selector:
    app: swapi-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
