steps:
  - label: "Install Orca scanning tool on runner"
    command: |
      echo -e "--- Installing \033[33mOrca Scanner\033[0m :heart:"
      sudo curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
  - label: "Building Image"
    command: |
      echo -e "--- Building Image :heart::heart::heart:"
      docker build . -t swapi 
  - label: "Running Scan"
    command: |
      echo "--- Running scan on branch $BUILDKITE_BRANCH "
      docker run -u 0 --rm -t -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/orcasecurity/orca-cli:latest -p happy-friday --api-token aHR0cHM6Ly9hcHAuYXUub3JjYXNlY3VyaXR5LmlvfHxJOUUyU0NXZFRTRFd0YllPMkYyd0hIMnhsY3hUODN3Nw==  image scan swapi 
    if: build.branch == "dev"
  - label: "Running scan on branch $BUILDKITE_BRANCH"
    command: orca-cli --api-token aHR0cHM6Ly9hcHAuYXUub3JjYXNlY3VyaXR5LmlvfHxJOUUyU0NXZFRTRFd0YllPMkYyd0hIMnhsY3hUODN3Nw== --project-key happy-friday-prod image scan swapi
    if: build.branch == "main"
  - label: "Running full scan"
    command: orca-cli --api-token aHR0cHM6Ly9hcHAuYXUub3JjYXNlY3VyaXR5LmlvfHxJOUUyU0NXZFRTRFd0YllPMkYyd0hIMnhsY3hUODN3Nw== --project-key happy-friday-prod image scan swapi
    if: build.message =~ /^full/
