steps:
  - label: "Install Sysdig scanning tool on runner"
    command: |
      echo -e "--- Installing \033[33mSysdig Scanner\033[0m :heart:"
      sudo curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
      sudo chmod 755 ./sysdig-cli-scanner
      sudo cp -p ./sysdig-cli-scanner /usr/local/bin

  - label: "Building Image"
    command: |
      echo -e "--- Building Image :heart::heart::heart:"
      docker build . -t swapi 
  - label: "Running scan on branch $BUILDKITE_BRANCH :buildkite: for repo $BUILDKITE_REPO :github:"
    command: |
      set -x
      id
      whoami
      API_TOKEN=\$(aws secretsmanager get-secret-value --secret-id svk/sysdig | jq -r .SecretString | awk -F '"' '{print \$4}') 
      sudo SECURE_API_TOKEN=$$API_TOKEN sysdig-cli-scanner  --apiurl https://app.au1.sysdig.com swapi
