steps:
  - label: "Install Orca scanning tool on runner"
    command: |
      echo -e "--- Installing \033[33mOrca Scanner\033[0m :heart:"
      sudo curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
  - label: "Building Image"
    command: |
      echo -e "--- Building Image :heart::heart::heart:"
      docker build . -t swapi 
  - label: "Running Scan"
    command: |
      echo "--- Running scan on branch $BUILDKITE_BRANCH "
      #ORCA_API_KEY=$(aws secretsmanager get-secret-value --secret-id prod/orca/buildkite | jq '.SecretString' | awk -F '"' '{print $3}' | awk -F '\' '{print $1}')
      docker run -u 0 --rm -t -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/orcasecurity/orca-cli:latest -p happy-friday --api-token $ORCA_API_KEY  image scan swapi 
    if: build.branch == "dev"
  - label: "Running scan on branch $BUILDKITE_BRANCH"
    command: orca-cli --api-token == --project-key happy-friday-prod image scan swapi
    if: build.branch == "main"
#  - label: "Running full scan"
#    command: orca-cli --api-token == --project-key happy-friday-prod image scan swapi
#    if: build.message =~ /^full/
