# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# TEST
name: Deploy to tetsuo

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  lint-check:
    name: lint-check
    # we had issues with ubuntu, currently using MacOS
    runs-on: ubuntu-latest
    steps:

      - name: Lint
        run: echo "Your linting goes here..."

  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:

    - name: format-check
      run: echo "Your format checking goes here..."

  unit-tests:
    needs: [lint-check,format-check]
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Your Unit tests go here..."

  debug-print-event-data:
    name: debug-print-event-data
    runs-on: ubuntu-latest
    steps:

    - name: Print event data for debug purposes
      env:
        EVENT: ${{ toJSON( github.event ) }}
      run: echo "$EVENT"

  Deploy-to-tetsuo:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Pull codebase
        run: |
          set -x
          curl -s -X POST -H "Content-Type: application/json" http://3.27.29.216:8080/pull -d '{"branch":"main","url":"https://github.com/codecowboydotio/swapi-json-server"}'
      - name: Apply application configuration
        run: |
          set -x
          curl -s -X POST -H "Content-Type: application/json" http://3.27.29.216:8080/pull -d '{"branch":"main","url":"https://github.com/codecowboydotio/swapi-json-server"}'
          curl -s -X POST -H "Content-Type: application/json" http://3.27.29.216:8181/app -d '{"port":"80","w_dir":"/apps/swapi-json-server","language":"node","name":"swapi-json-server"}'


